version: "1.0"
info:
  model: int-scaffold
packages:
- name: TechXDemoProject
  gitServerName: myGithub
  gitUrl: https://github.com/johnlyng
  gitUsername: johnlyng
  gitBranch: main
- name: OpenWeatherClient
  gitServerName: myGithub
  gitUrl: https://github.com/rahuldemocenter
  gitUsername: johnlyng
  gitBranch: main
